config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:edit, :update, :show]
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
    resources :tags, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :message, :image, presence: true

  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :post_tags
  has_many :tags, through: :post_tags

  #投稿が「いいね」されたかをチェック
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # Comment.create(comment_params)
    # redirect_to post_path(params[:post_id])
    # redirect_to root_path
    # @comment = Comment.create(comment_params)
    # respond_to do |format|
    #   format.json
    # end
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, post_id: params[:post_id])
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.build(post_id: params[:post_id])
    like.save
    # redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    # redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
    @post = Post.new
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end
  
  def new
    
  end

  def create
    Post.create(post_params)
    redirect_to root_path

    # @post = Post.create(post_params)
    # @post = Post.new(post_params)
    # if @post.save
    #   respond_to do |format|
    #     format.json
    #   end
    # end
  end

  private
  def post_params
    params.require(:post).permit(:image, :tag, :message).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id]) 
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @posts = user.posts
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="headerContents">
        <p class="headerContents__logo"><%= link_to "PersonalApp", root_path %></p>
        <% if user_signed_in? %>
          <div class="user">
          <div class="user__name">
            <span><%= link_to "#{current_user.nickname}", user_path(current_user) %></span>
          </div>
          <div class="user__info">
            <div class="user__info-box user__info-edit"><%= link_to "Edit", edit_user_path(current_user) %></div>
            <div class="user__info-box user__info-logout"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></div>
          </div>
        </div>
        <% elsif request.path.include?("sign_in") %>
        <% elsif request.path.include?("sign_up") %>
        <% else %>
          <div class="user">
            <div class="user__info">
              <div class="user__info-box user__info-signup"><%= link_to "Sign up", new_user_registration_path %></div>
              <div class="user__info-box user__info-login"><%= link_to "Log in", new_user_session_path %></div>
            </div>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer class="footer">
      <p class="footer__txt">
        Copyright PersonalApp 2020.
      </p>
    </footer>

  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if post.liked_by?(current_user) %>
    <div class="main-content__logo-fas"><%=link_to post_likes_path(post.id), class: "likeBtn", method: :delete, remote: true do %><i class="fas fa-heart"></i><% end %></div>
  <% else %>
    <div class="main-content__logo-far"><%=link_to post_likes_path(post.id), class: "likeBtn", method: :post, remote: true do %><i class="far fa-heart"></i><% end %></div>
  <% end %>
<% else %>
  <div class="main-content__logo-far"><i class="far fa-heart"></i></div>
<% end %>
<div class="likes_count">LIKE数<span><%= post.likes.count %></span></div>

app/views/likes/create.js.erb
$(function(){
$('#like_btn_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");
})

app/views/likes/destroy.js.erb
$('#like_btn_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/_content.html.erb
<div class="main-content">
  <div class="main-content__userName">
    <%= post.user.nickname %>
  </div>
  <%= link_to post_path(post.id), method: :get do %>
    <div class="main-content__image">
      <img src="<%= post.image %>">
    </div>
  <% end %>
  <div class="main-content__icons">
    <div class="like_block" id="like_btn_<%= post.id %>">
      <%= render partial: 'likes/like', locals: {post: post} %>
    </div>
    <div class="main-content__logo"><%= link_to post_path(post.id), method: :get do %><i class="far fa-comment"></i><% end %></div>
  </div>
  <div class="main-content__text">
    <div class="main-content__text-userName"><%= post.user.nickname %></div>
    <%= post.message %>
  </div>
  <div class="main-content__tags">
  <% if post.tag? %>
    #<%= post.tag %>
  <% end %>
  </div>
</div>

app/views/posts/_img.html.erb
<div class="posted-images">
  <img src="<%= post.image %>">
</div>

app/views/posts/_main.html.erb
<div class="main-contents">
  <% @posts.each do |post| %>
    <%= render partial: "content", locals: { post: post } %>
  <% end %>
  <%= paginate(@posts) %>
</div>

app/views/posts/_sub.html.erb
<div class="sub__content">
  <%# <%= link_to "投稿", new_post_path, class: "postBtn" %>
  <%= form_for @post, html: {id: "form_ajax"} do |f| %>
    <p class="input__form__img">
      Image：<%= f.text_field :image, placeholder: "Image Url", class: "img_ajax" %>
      <%# Image：<input type="text" name="img" size="20" placeholder="img"> %>
    </p>
    <p class="input__form__msg">
      Text：<%= f.text_area :message, placeholder: "message", class: "msg_ajax" %>
      <%# Text：<textarea type="text" name="msg" rows="4" cols="25" placeholder="text"></textarea> %>
    </p>
    <p class="input__form__tag">
     Tag：<%= f.text_field :tag, placeholder: "message", class: "tag_ajax" %>
    </p>
    <%# <p class="input__form__tag">
      Tags：<input type="text" name="tag" size="20" placeholder="#タグ">
    </p> %>
    <p class="input__form__submit">
      <%= f.submit "Submit", class: "input__form__submit-btn" %>
      <%# <input type="submit" value="submit" class="input__form__submit-btn"> %>
    </p>
  <% end %>
</div>

app/views/posts/_sub_test.html.erb
<div class="sub__content">
  <%= form_for(model: @tweet, local: true) do |f| %>
    <div class="field">
      <div class="field__label">
        <%= f.label :image %>
      </div>
      <div class="field__input">
        <%= f.text_field :image, placeholder: "Image Url" %>
      </div>
    </div>
    <div class="field">
      <div class="field__label">
        <%= f.label :text %>
      </div>
      <div class="field__input">
        <%= f.text_area :text, placeholder: "text" , rows: "10" %>
      </div>
    </div>
    <div class="field">
      <div class="field__label">
        <%= f.label :name %>
      </div>
      <div class="field__input">
        <%= f.text_field :name, placeholder: "＃タグ" %>
      </div>
    </div>
    <div class="action">
      <%= f.submit "SUBMIT" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <%= render "main" %>
  <%= render "sub" %>
</div>

app/views/posts/new.html.erb
<div class="sub__content">
  <%= form_for @post do |f| %>
    <p class="input__form__img">
      Image：<%= f.text_field :image, placeholder: "Image Url" %>
      <%# Image：<input type="text" name="img" size="20" placeholder="img"> %>
    </p>
    <p class="input__form__msg">
      Text：<%= f.text_area :message, placeholder: "message" %>
      <%# Text：<textarea type="text" name="msg" rows="4" cols="25" placeholder="text"></textarea> %>
    </p>
    <%# <p class="input__form__tag">
      Tags：<input type="test" name="tag" size="20" placeholder="#タグ">
    </p> %>
    <p class="input__form__submit">
      <%= f.submit "Submit", class: "input__form__submit-btn" %>
      <%# <input type="submit" value="submit" class="input__form__submit-btn"> %>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="one-post">
  <div class="main-content">
    <div class="main-content__userName">
      <%= @post.user.nickname %>
    </div>
    <div class="main-content__image">
      <img src="<%= @post.image %>">
    </div>
    <div class="main-content__icons">
      <% if @post.likes.count >= 2%>
        <div class="likes_count"><span><%= @post.likes.count %></span> LIKES</div>
      <% else %>
        <div class="likes_count"><span><%= @post.likes.count %></span> LIKE</div>
      <% end %>
    </div>
    <div class="main-content__text">
      <div class="main-content__text-userName"><%= @post.user.nickname %></div>
      <%= @post.message %>
    </div>
    <div class="main-content__tags">
      tagtagtagtagtagtagtagtagtag
    </div>
    <div class="main-content__comments">
      <p class="main-content__comments-ttl">comment</p>
      <div class="comments__container">
        <% if current_user %>
          <%= form_for [@post, @comment], html: {id: "comment_ajax"} do |f| %>
            <%= f.text_area :comment, placeholder: "コメントする", class: "cmt-box", rows: "3" %>
            <%= f.submit "SEND", id: "cmt-btn" %>
          <% end %>
        <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
      </div>
      <div class="comments-area">
        <p>＜コメント一覧＞</p>
        <% if @comments %>
          
          <div class="comments-list">
            <% @comments.each do |comment| %>
              <p>
                <span><%= comment.user.nickname %></span>：<%= comment.comment %>
              </p>
            <% end %>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div id="acount-page" class="acount-page">
<div class="contents">
    <div class="contents__left">
      <h1 class="contents__left-ttl">Edit account</h1>
    </div>
    <div class="contents__right">
      <%= form_for(current_user) do |f| %>
        <div class="field">
          <%= f.label :nickname, class: "field-label" %><br />
          <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" %>
        </div>

        <div class="field">
          <%= f.label :email, class: "field-label" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>

        <div class="actions">
          <%= f.submit "Update", class: "login-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="myPage">
  <div class="container">
    <h1 class="container__ttl">My Page</h1>
    <div class="container__imgBox">
      <% @posts.each do |post|%>
        <%= render partial: "posts/img", locals: { post: post } %>
      <% end%>
    </div>
  </div>
</div>